### ISSUE TITLE
Page not found error for browser refresh

### ISSUE THREAD

**Issue by malinda1986** [vercel/serve#444]
I'm having a problem with refreshing the browser in specific URL (ex: http://localhost:5000/user) gives the page not found error. If I access that URL via hyperlink it works.
Note: its single page React app 
Any help or advice appreciate

**Comment by nicolasparada** [comment]
`serve -s` or `serve --single` to serve single page applications.

**Comment by malinda1986** [comment]
work perfectly , thanks

**Comment by ykhandor** [comment]
serve -s or serve --single does not work for me. Still get a 404 not found error.
P.S. It is an Angular 6 app.
npm version: 6.4.1
Node version: 10.15.1

**Comment by nicolasparada** [comment]
That's another issue (#507) in the last version.
Try installing version 10.1.1 until is fixed.
```bash
npm i -g serve@10.1.1
```

**Comment by ykhandor** [comment]
@nicolasparada - That worked. Thanks a lot! 👍

**Comment by AlessandroVetere** [comment]
Bug still present on serve version 10.1.2 on Windows 10 64 bit, Node v10.15.0.

**Comment by leerob** [comment]
Looks like this has been resolved 👍
