### ISSUE TITLE
Security Issue - Open redirect possible with serve@9.2.0

### ISSUE THREAD

**Issue by facos86** [vercel/serve#449]
THere is a security issue with serve@9.2.0 serving a React project in docker.

If you test this url, it will redirect you to the "evil" url
https://yourwebsite//www.yourtango.com/2017307353/16-signs-person-evil-and-you-need-stay-away.html

Tested in Sarari,Chrome Incognito mode

**Comment by xxczaki** [comment]
You should probably contact Zeit directly.

**Comment by Axelen123** [comment]
I tried it with an angular project (serve -s dist/PROJECT) and it works

**Comment by leerob** [comment]
Closing as stale 🙏
