### ISSUE TITLE
Page returns plain text on reload with service worker

### ISSUE THREAD

**Issue by praburangki** [vercel/serve#455]
<img width="1280" alt="screen shot 2018-07-25 at 4 45 47 pm" src="https://user-images.githubusercontent.com/8610935/43189861-38ca81fe-902a-11e8-8b6e-52c88055f4a2.png">

Serve version: 9.3.0

First load of the page works fine, but if i refresh it, it returns that plain text. If I hard refresh it, it works fine again.

I'm using it with workbox and this is my `serve.json` file:
```
{
  "public": "build",
  "headers": [
    {
      "source": "service-worker.js",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "no-cache"
        }
      ]
    }
  ]
}
```

I've also tried to set the value to `max-age=0` or `null` but that didn't help.

**Comment by IzaacBarratt** [comment]
Having the same issue while using react. Not sure how to deal with it

**Comment by leerob** [comment]
Closing as stale 🙏
