### ISSUE TITLE
can not jump to Chinese URI

### ISSUE THREAD

**Issue by builden** [vercel/serve#458]
serve version: v9.4.0

```html
<body>
  <a href="中文.html">中文URL</a>
</body>
```

when click the link, get the error info:
(node:48768) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: The header content contains invalid characters

**Comment by leerob** [comment]
Closing as stale 🙏 Please include a reproduction if you've like to reopen this. Thank you!
