### ISSUE TITLE
Use rewrite routing segments with query string

### ISSUE THREAD

**Issue by nathanbirrell** [vercel/serve#466]
Is there a way for me to get something like this working?

```json
{
  "cleanUrls": false,
  "rewrites": [
    {
      "source": "/products?search=:query",
      "destination": "/products/search-:query.json"
    }
  ]
}

```

Ideally this way I could create a mock for each search query I want.

**Comment by jessehattabaugh** [comment]
Which part of this isn't currently supported? just the ':query' part? Or are query params not supported in rewrites at all?

**Comment by nbirrell-bom** [comment]
The latter. It seems anything after a query string (`?search=...`) is ignored.

This is particularly apparent when I have a rewrite set for `/products`, because any calls made with the _search_ query are matching the `/products` rewrite. Not ideal.

**Comment by nathanbirrell** [comment]
The latter. It seems anything after a query string (?search=...) is ignored.

This is particularly apparent when I have a rewrite set for `/products`, because any calls made with the search query are matching the `/products` rewrite. Not ideal, they should be matching the `/products?search=:query` rewrite.

**Comment by leerob** [comment]
Closing as stale 🙏
