### ISSUE TITLE
serving file unable on macOS

### ISSUE THREAD

**Issue by ac88** [vercel/serve#473]
at windows 7 command-line interface,

`serve examples\counter-vanilla\index.html` success

but macOS

it's error.

node_modules\serve\bin\serve.js:241

```js
try {
  content = await readFile(location, 'utf8');
} catch (err) {
  if (err.code === 'ENOENT') {
    continue;
  }

  console.error(error(`Not able to read ${location}: ${err.message}`));
  process.exit(1);
}
```

windows 7 ,err.code === 'ENOENT'

but macOS err.code is 'ENOTDIR'

windows 7 node version 10.x

macOS 10.13.6 ,node v10.9.0

**Comment by leerob** [comment]
Closing as stale 🙏 Please include a reproduction if you've like to reopen this. Thank you!
