### ISSUE TITLE
Serving with mapped CIFS drives

### ISSUE THREAD

**Issue by vuchl** [vercel/serve#478]
I am using `serve` on a Windows machine. I have the config file like this
```json
{
  "unlisted": [
    "folder1",
    "another folder"
  ]
}
```

at `C:\config-files\static-files-1\serve.json`.

The directory I want to serve is at `L:\folder\servable-content`.
I now want to run the serve command from a script or just another working directory like so:
```cmd
C:\>serve -l 8081 -c C:\config-files\static-files-1\serve.json L:\folder\servable-content
```

but now the serve.json is not recognized (the message "INFO: Discovered configuration in `C:\config-files\static-files-1\serve.json`" is missing).

I also tried it the other way around: running `serve` from the `L:\folder\servable-content` directory and pointing to the config file. But this also did not result like I wanted it to.

The only thing working was putting the `serve.json` it the serving directory or when both, config and servable directory, are on the same drive.

Any ideas what else I can do? I don't want to pollute the servable directory with the config file.

**Comment by leerob** [comment]
Closing as stale 🙏 Sorry for the slow response here.

**Comment by vuchl** [comment]
Does this mean it works now?
