### ISSUE TITLE
Serve Config Header for Content-Security-Policy doesn't accept URI with query string

### ISSUE THREAD

**Issue by shukii** [vercel/serve#494]
When adding a Content-Security-Policy header with a report-uri, the uri I need also has a query string

`report-uri https://xyz.com/api/12345/asdf?key=12345`

However when running serve, I'm getting a regex issue:

```
ERROR: The configuration you provided is wrong:
should match pattern "^[a-zA-Z0-9_!#$%&'*+.;/:, =^`|~-]+$"
{"pattern":"^[a-zA-Z0-9_!#$%&'*+.;/:, =^`|~-]+$"}
```

**Comment by leerob** [comment]
Closing as won't fix, but happy to review a PR if you want to tackle this 🙏
