### ISSUE TITLE
Dependencies Broken [flatmap-stream] Extracting tar content of undefined failed

### ISSUE THREAD

**Issue by oeduardoal** [vercel/serve#495]
When I try install the package serve, I will receive a message: 

[package] flatmap-stream

```
$ yarn global add serve
yarn global v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by pacocoursey** [comment]
The flatmap-stream package was recently involved in a security incident. It is now removed and under management by npm.

From the new security README:

> This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.

Try installing `serve` again.
