### ISSUE TITLE
Relative path for unix socket listening broken

### ISSUE THREAD

**Issue by oklas** [vercel/serve#512]
Relative path does not worked, serve **loses a dot** and tries to use an absolute path instead of a relative:

```sh
serve -l unix:./var/serve.sock ./build
```
> ERROR: Failed to serve: Error: listen EACCES /var/serve.sock

Same time micro is worked:

```sh
micro -l unix:./var/service.sock src/service/service.js
```
> micro: Accepting connections on ./var/service.sock

micro 9.3.3
serve 10.1.2

**Comment by leerob** [comment]
Please include a repro example, thank you! 🙏 Closing for now, happy to re-open if more info is provided.
