### ISSUE TITLE
Serve 11 cannot set symlinks to true in config.json

### ISSUE THREAD

**Issue by AaronFriel** [vercel/serve#519]
`serve@^11`  currently errors out when setting `symlinks: true`:

```
root@c3ee02fdad56:/app# serve --version
11.0.0
root@c3ee02fdad56:/app# serve -p 8000 -c ./serve.json
INFO: Discovered configuration in `./serve.json`
ERROR: The configuration you provided is wrong:
should NOT have additional properties
{"additionalProperty":"symlinks"}
```

**Comment by joeldenning** [comment]
I am also experiencing this issue.

**Comment by joeldenning** [comment]
I created a PR that will fix this. https://github.com/zeit/schemas/pull/53

**Comment by joeldenning** [comment]
I don't represent vercel but do not think it's helpful to express anger or sarcasm over this. This is an open source project and the maintainers of it owe us nothing.

**Comment by warren-bank** [comment]
_shameless self-promotion alert_:<br>this feature is fixed in my [`@warren-bank/serve`](https://github.com/warren-bank/node-serve) fork of `serve`

**Comment by steve-taylor** [comment]
Symlinks don't work at all, even when specified from the command line.

Both of these fail to serve symlinks:

```sh
serve --symlinks
```

```sh
serve -S
```

**Comment by thedapperdev** [comment]
any news on this please? @leo
