### ISSUE TITLE
serve.json not work

### ISSUE THREAD

**Issue by dimka11** [vercel/serve#522]
index.js
```
const handler = require('serve-handler');
const http = require('http');

 
const server = http.createServer((request, response) => {
  // You pass two more arguments for config and middleware
  // More details here: https://github.com/zeit/serve-handler#options
  return handler(request, response,
   );
})
 
server.listen(3000, () => {
  console.log('Running at http://localhost:3000');
});
```
serve.json:
```
{
    "public":  "./static"
}
```
in same directory with index.js

running:
`node index.js from project directory`

result: not working

Also I have question, how can I serve multiple directory?

**Comment by aulisius** [comment]
Hi,

Since you're using `serve-handler`, you don't need to provide `serve.json` separately.

You can do something like this

```js
const handler = require('serve-handler');
const http = require('http');
const serveOptions = { public: "./static" }; 
const server = http.createServer((request, response) => {
  // You pass two more arguments for config and middleware
  // More details here: https://github.com/zeit/serve-handler#options
  return handler(request, response, serveOptions);
})
 
server.listen(3000, () => {
  console.log('Running at http://localhost:3000');
});
```

`serve-handler` accepts a third argument where you can pass the same options that are available through `serve.json`.

**Comment by qiqingfu** [comment]
@aulisius How To configure the proxy correctly

**Comment by aulisius** [comment]
@qiqingfu I haven't really tried setting proxy with `serve` but you can try using `rewrites` mentioned as one of `serve-handler` options -> https://github.com/zeit/serve-handler#rewrites-array

**Comment by qiqingfu** [comment]
@aulisius Thank you

**Comment by leerob** [comment]
This was solved!
