### ISSUE TITLE
Default view configuration

### ISSUE THREAD

**Issue by LosEagle** [vercel/serve#532]
I was wondering if someone would be willing to implement a configuration option for default view. Right now when I'm browsing directories, I'm getting a grid view which shortens names more than I'd like.   
   
Well that's what the view switch is there for right? Yeah, and it does its job well. The problem is I need to toggle it every single time I navigate somewhere else. Having an option in `serve.json` to set it to list view by default would be welcome addition to those of us who prefer it.

**Comment by leerob** [comment]
Closing this as won't fix 🙏 Thank you for your suggestion.
