### ISSUE TITLE
Error on WSL

### ISSUE THREAD

**Issue by Berkmann18** [vercel/serve#533]
When I run `serve .` on WSL (Ubuntu 18.04.1 on Windows 10 with the kernel v4.4.0), I get this output:
```shell
ERROR: Cannot copy to clipboard: Command failed: xsel --clipboard --input
xsel: Can't open display: (null)
: Connection refused
```

I tried setting `DISPLAY=localhost:0` but that doesn't help.

**Comment by chase-moskal** [comment]
`serve` automatically copies the local address to the clipboard

it looks like this automatic feature is failing on your machine

you can supply the `-n` flag to tell `serve` to skip the clipboard step, which may help you

try:

    serve -n

let us know if this solves the issue for you :wave:

**Comment by Berkmann18** [comment]
It does indeed __ignore that__ but it doesn't solve per se.

**Comment by adriangabardo** [comment]
@Berkmann18 I also run serve from WSL, and it is not an operation-critic feature, as chase-moskal said, you can run the `-n` flag so that it doesn't try to put on the clipboard.

**Comment by rfgamaral** [comment]
Same issue here, but the root cause is actually [here](https://github.com/sindresorhus/clipboardy/issues/53).

**Comment by Berkmann18** [comment]
@adriangabardo True, it's not an operation-critic thing but noisy and which leaves room for (potential) bugs (especially as the solution is just a workaround).
