### ISSUE TITLE
[Feature] add an option to display ORCode of url?

### ISSUE THREAD

**Issue by sjfkai** [vercel/serve#537]
What about to add an option to display OR code of url?

Transfer files to the phone is a commonly used feature. If we can scan a QR code, we don't have to type url any more.

**Comment by sjfkai** [comment]
If you want this feature, you can use `serve-qrcode` temporarily.

```sh
# install
npm i serve-qrcode
# then
serve-qrcode -q
```

**Comment by leerob** [comment]
Closing as won't fix, as the project isn't actively adding new features 🙏
