### ISSUE TITLE
Can we have hot reload for serve?

### ISSUE THREAD

**Issue by dotku** [vercel/serve#571]
I think serve is great, but it doesn't have hot reload which might be slight inconvenient for developer. Anyone know if we can enhance hot reload for serve or alternative package?

**Comment by salazarm** [comment]
Use a Next server for local development and export the app to a SPA app and serve it with whatever you want

**Comment by HP4k1h5** [comment]
i edited the shebang of `which serve` to look for nodemon. 

```bash
cat $(which serve) | head -n1
# -> #!/usr/bin/env nodemon
```

**Comment by jeanlucaslima** [comment]
Could this be added just as a simple configuration or flag?

**Comment by revelt** [comment]
> Anyone know if we can enhance hot reload for serve or alternative package?

I switched to [`live-server`](https://www.npmjs.com/package/live-server), it does hot reload.

I guess it's _business_. Vercel as a corporation wants us to use vercel CLI and next.js.

**Comment by dotku** [comment]
Thanks for all respond, it seems there are several alternative options here. I want to contribute my found. Actually "react-scripts" support live load/hot  load too (and you don't have to use react).

Let me close this issue for now :)

**Comment by moaz-mokhtar** [comment]
Simplest solution I found is `live-server`:

```
# Install live-server
npm install -g live-server

# run it
live-server
```
