### ISSUE TITLE
No response for invalid configuration / configuration file path.

### ISSUE THREAD

**Issue by samuelimoisili** [vercel/serve#604]
It gives no feedback for invalid configurations or configuration file not found. It only gives feedback if it finds the configuration file.

I feel a bit of feedback would be good for the end-users.

**Comment by mundanelizard** [comment]
Okay,

Is anyone interested in doing this. I am new here and was wondering if I could work on this issue.

**Comment by alium0978** [comment]
Does this means someone would be working on it?
