### ISSUE TITLE
"@zeit/schemas" cannot be found in the npm-registry

### ISSUE THREAD

**Issue by ca057** [vercel/serve#622]
When running `npx serve`, I get an error that `@zeit/schemas@2.6.0` cannot be found:

```sh
$ npx serve                                                                                                                                                                                     npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@zeit%2fschemas - Not found
npm ERR! 404
npm ERR! 404  '@zeit/schemas@2.6.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'serve'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-07-29T20_24_27_364Z-debug.log
Install for [ 'serve@latest' ] failed with code 1
```

As far as I can tell, this happens because [`@zeit/schemas`](https://www.npmjs.com/package/@zeit/schemas) cannot be found anymore in the npm registry. As the [`yarn.lock` file is pointing to an entry in the yarn-registry](https://github.com/vercel/serve/blob/master/yarn.lock#L27), a global installation via `yarn` is still working.

Is `npm`/`npx` not supported anymore?

I’m happy to provide more information if needed or help with updating packages, but I guess we would need to have "@zeit/schemas" in the npm registry again :)

---
Environment:

* macOS v10.15.5
* Node.js v14.4.0
* npm 6.14.6

**Comment by krasimir** [comment]
Hey, I'll double  the report:
```
ᐅ yarn global add serve
yarn global v1.21.1
[1/4] 🔍  Resolving packages...
error Couldn't find package "@zeit/schemas@2.6.0" required by "serve" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
Same result if I use `npm i serve -g`.

**Comment by krasimir** [comment]
Or maybe it's a problem of npm. It's a bit weird that this issue is reported 8 days ago and I (we) are experiencing just now. Also today I'm seeing
![image](https://user-images.githubusercontent.com/528677/89522821-83191680-d7ea-11ea-9677-f865a90293fe.png)

**Comment by sorenhoyer** [comment]
We also just ran into this bug just now

**Comment by krasimir** [comment]
I think it's definitely a npm issue
![image](https://user-images.githubusercontent.com/528677/89523147-12bec500-d7eb-11ea-9296-6df4657eca79.png)
(with scoped packages)

**Comment by dheeraj-jn** [comment]
It's not specific to `npm`, even `yarnpkg` has a problem.
I'm using `yarn` and I get a `404` when `yarn install` tries to fetch https://registry.yarnpkg.com/@zeit/schemas/-/schemas-2.6.0.tgz

**Comment by pereznieto** [comment]
We're seeing this too, both locally and on CI/CD (CircleCi – Ubuntu). Our automated pipeline was working up to a couple of hours ago or so, and then it stopped working all of a sudden because of the above problem.
Tried to run locally (macOS 10.15.4, Node.js v13.9.0, npm 6.14.5) and seeing the same.

**Comment by dheeraj-jn** [comment]
It's working now. It's perhaps a temporary server glitch.

**Comment by krasimir** [comment]
> NPM: Errors are decreasing while we re-populate a faulty cache. We are working to speed up that process to fully resolve the remaining issues quickly.
So I guess one by one all the packages will be fixed.

**Comment by ca057** [comment]
Well, this escalated quickly. I think the error I got is unrelated to what happened today, but I can install `serve` via `npx` again. The issue is therefore fixed for me.

**Comment by krasimir** [comment]
Yep. It works on our side too.
