### ISSUE TITLE
Forbid to show folder contents option

### ISSUE THREAD

**Issue by dkaraush** [vercel/serve#632]
By default, if folder doesn't contain index.html file, it shows all files in it with links.
I tried to find any options, that would restrict that and would show 403 or a similar error, but I didn't find any of those.
Is there any option that would forbid to watch folder content?

**Comment by r0mflip** [comment]
Add a `serve.json` file to the root folder of your project and add to it:
``` json
{
    "directoryListing": false
}
```

This disables any directory listing.

https://github.com/vercel/serve-handler#directorylisting-booleanarray

**Comment by dkaraush** [comment]
Oh, thanks for the answer, sorry for an obvious question from FAQ; I thought it should be configured in CLI
Closing an issue.
