### ISSUE TITLE
How to setup port in serve.json?

### ISSUE THREAD

**Issue by fdorantesm** [vercel/serve#653]
I trying to serve a react build directory using a file `serve.json` but i didn't found documentation related except config schema, but it doesn't have a port.

https://github.com/vercel/schemas/blob/master/deployment/config-static.js

**Comment by yiliansource** [comment]
@fdorantesm I found that you can set a specific port by using `serve <dir> -l <port>`, for example with `serve out -l 80`. Hope this helps.

**Comment by heidemn** [comment]
See also `npx serve --help` .

**Comment by leerob** [comment]
Looks to be resolved, thank you all!
