### ISSUE TITLE
Command not recognized

### ISSUE THREAD

**Issue by fabraga** [vercel/serve#682]
Hi, 

I am coming here today to try and find out why I am able to successfully install "serve" (npm i -g serve) but the command is never recognized when I run it. I have installed it quite a good number of times, including as admin in Windows Powershell. It installs, no problem! But it never runs. Why it installs but never gets recognized as command when I try to run it?

Thank you.

**Comment by warren-bank** [comment]
is `%NODE_PATH%\.bin` in your `PATH`?

where the default `NODE_PATH` is: `npm root -g`

**Comment by leerob** [comment]
Closing as it seems resolved and related to your machine 🙏
