### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by zvone00** [vercel/serve#684]
Is there any way to force HTTPS with serve, so that the user is redirected if he lands to HTTP page?

**Comment by warren-bank** [comment]
_shameless self-promotion alert_:<br>this feature is available in my [`@warren-bank/serve`](https://github.com/warren-bank/node-serve) fork of `serve`

see: the `--force-https` option

**Comment by reed665** [comment]
> _shameless self-promotion alert_:this feature is available in my [`@warren-bank/serve`](https://github.com/warren-bank/node-serve) fork of `serve`
> 
> see: the `--force-https` option

tried to run it via npm script but no luck 🤔 

```bash
yarn run v1.22.17
$ @warren-bank/serve --force-https 8080 ./dist
The system cannot find the path specified.
error Command failed with exit code 1.
```

**Comment by warren-bank** [comment]
> @reed665 
> RE:  using [`@warren-bank/serve`](https://github.com/warren-bank/node-serve) fork of `serve`

1. the name of the binary is still `serve`
2. `--force-https` is only useful when running a secure endpoint by combining with either:
   * `--ssl-cert` and `--ssl-key` to use your own certificate
   * `--ssl` to use a generic self-signed certificate that comes included

ex:
```bash
serve --ssl -l 443 --force-https 80 ./dist
```

now:
```bash
curl -I 'http://localhost:80/'
```

returns:
```bash
HTTP/1.1 301 Moved Permanently
Location: https://localhost:443/
```

**Comment by n-studio** [comment]
@warren-bank Can you make a PR for it?

**Comment by leerob** [comment]
This project is mostly in maintenance mode, with security updates and patches being accepted. If you are willing to open a PR, I'm happy to reopen this and explore!

**Comment by alumbo** [comment]
You could use redirection http to https with configuration file `serve.json`

```{
  "redirects": [
    {
      "source": "/(.*)/?",
      "destination": "https://yourdomainhere.com/$1",
      "type": 301
    }
  ]
}
