### ISSUE TITLE
Liitle bit server side dynamics

### ISSUE THREAD

**Issue by prkeshri** [vercel/serve#690]
Hi

I hosted a project of mine in some service provider (I may name if required), and saw that they are using serve in order to serve my pages. Fair enough, but, there are issues with SPAs like those ones built on React. One such issue is the rendering of meta and title tags. Some of the problems can be resolved by using react components etc. in browsers, but what about when we share a dynamically rendered article, say in Whatsapp or Facebook? The title shown is of the index.html. Period. Nothing can be done over here.

Hence, my proposal is to enable little bit server dynamics, so atleast we can address these kinds of issues without having to go for a full fledge nodejs or php etc. solution.

If you like my proposal, I am happy to start working on the same (of course, post some initial discussions), maybe we could inject some middleware scripts in runtime and alter the behaviour.

Please let me know as I am eager for a response and excited to work on the same.

PS: I saw another; maybe related, kind of; issue while browsing through the same: https://github.com/vercel/serve/issues/670.

**Comment by leerob** [comment]
This project is mostly in maintenance mode, with security updates and patches being accepted. If you are willing to open a PR, I'm happy to reopen this and explore!
