### ISSUE TITLE
How to deploy to Vercel CDN

### ISSUE THREAD

**Issue by oraqlle** [vercel/serve#694]
Hi there, 
I was just wondering how and if it were possible to use 'serve' on the Vercel CDN as a standalone application. ie. so that I could go to the remote URL given by Vercel and view the contents of a specified directory (within the project) as opposed to looking at it on localhost.

If it is possible, how would I go about creating this. I'm sorry if this is a very trivial matter but I'm not very used to web development of any kind. Thanks.

**Comment by leerob** [comment]
It's not currently possible 🙏
