### ISSUE TITLE
Update message has malformed `chalk` output

### ISSUE THREAD

**Issue by leerob** [vercel/serve#711]
### Description

```
▲  serve/ serve -v
 {bgRed.white  UPDATE } The latest version of `serve` is , 14.0.0-canary.0
14.0.0
```

### Library version

14.0.0

### Node version

16.13.1

**Comment by leerob** [comment]
Seems it's in `--help` too 🙏 

<img width="777" alt="CleanShot 2022-07-12 at 11 31 24@2x" src="https://user-images.githubusercontent.com/9113740/178545335-4c3d576a-a0a7-4991-a9ed-e8058e519608.png">

**Comment by gamemaker1** [comment]
It looks like chalk split the tagged template functionality into a separate module called `chalk-template`, we should be importing and using that for the update and help messages.
