### ISSUE TITLE
Syntax Error: ?? in main.js 

### ISSUE THREAD

**Issue by vsinghal3392222** [vercel/serve#718]
### Description

Check main.js

### Why

Check main.js

### Alternatives

Check main.js

**Comment by vsinghal3392222** [comment]
I think node 12 issue

**Comment by owen-duncan-snobel** [comment]
I am getting the same issue and have tried with a node v12 and node v14 version and both gave the same syntax error

**Comment by gamemaker1** [comment]
This is definitely a Node 12 issue as support for the `??` operator was added in Node 14. @owen-duncan-snobel could you please create a new issue with the bug report template and share the exact Node version, `serve` version and the error that you see?
