### ISSUE TITLE
support both http and https

### ISSUE THREAD

**Issue by jasonwee** [vercel/serve#765]
### Description

would it be possible to request to support both http and https at the same time?

```
 ./node_modules/.bin/serve -d  -l 8080  -s build/ -l 8443 --ssl-cert mycert.crt --ssl-key mykey.crt
```
where -l 8080 is http
and -l 8443 is https

### Why

because there are some requests only require http and some request require https. So it would be best to support both protocols.

### Alternatives

https://stackoverflow.com/questions/8355473/listen-on-http-and-https-for-a-single-express-app

**Comment by AdrianMrn** [comment]
Couldn't you run both commands at the same time using something like [concurrently](https://www.npmjs.com/package/concurrently)?

**Comment by jasonwee** [comment]
okay, sure, thank you.
