### ISSUE TITLE
Restore silent mode

### ISSUE THREAD

**Issue by minimit** [vercel/serve#780]
### Description

The `--silent` option is gone from the console command, also in `--help`.

Can you consider re-adding it? see #118 

### Why

For cypress tests, can't see the test on console it's full of serve outputs

### Alternatives

There are no alternative, I'm using nextjs 13 with `output: 'export',` and I need this package to serve the website

**Comment by Vovencia** [comment]
You can use the "--no-request-logging" flag
It disables console output:
Example command (windows): `SET NODE_ENV=production&& serve --no-request-logging .`

Using "NODE_ENV=production" simplifies the initial output to the console:
![image](https://github.com/vercel/serve/assets/17987999/6ad5262f-14b6-4ae6-b16e-57f4ac2070dd)

---

Вы можете использовать флаг "--no-request-logging"
Он отключает вывод в консоль

Использование "NODE_ENV=production" упрощает начальный вывод в консоль

**Comment by minimit** [comment]
Thanks
