### ISSUE TITLE
Node.js 21: "[DEP0040] DeprecationWarning: The `punycode` module is deprecated."

### ISSUE THREAD

**Issue by MikeMcC399** [vercel/serve#789]
### Description

Running `serve` under [Node.js](https://nodejs.org/en) `21.x` version causes the following deprecation notice to be displayed:

> (node:24848) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)

The message is also shown in response to `serve -v`.

[Node.js v21.0.0 (Current)](https://nodejs.org/en/blog/release/v21.0.0) was released on Oct 17, 2023.

#### Steps to reproduce

```bash
npm install serve -g
export NODE_OPTIONS='--trace-deprecation'
serve -v
```

shows

```text
added 89 packages in 8s

24 packages are looking for funding
  run `npm fund` for details
(node:4213) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/mike/n/lib/node_modules/serve/node_modules/fast-url-parser/src/urlparser.js:401:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
14.2.1
```

https://nodejs.org/dist/latest-v21.x/docs/api/deprecations.html#DEP0040 lists the deprecation and shows that a runtime deprecation was added to Node.js `v21.0.0` (see https://github.com/nodejs/node/pull/47202).

### Library version

First reported on version: `14.2.1`
Still reproducible with version: `14.2.2`

### Node version

~~v21.0.0~~
`v21.7.3`

### Related issues

- https://github.com/vercel/serve-handler/issues/204
- https://github.com/petkaantonov/urlparser/issues/20. This is the repo corresponding to the npm module [fast-url-parser](https://www.npmjs.com/package/fast-url-parser) implicated in the deprecation trace.

**Comment by MikeMcC399** [comment]
The [serve](https://www.npmjs.com/package/serve) dependency [fast-url-parser](https://www.npmjs.com/package/fast-url-parser) can be patched as a temporary measure. Starting with the following:

```bash
mkdir serve-test
cd serve-test
npm init -y
npm install serve
export NODE_OPTIONS='--trace-deprecation'
npx serve -v
```

## Workaround

Use npm module [patch-package](https://www.npmjs.com/package/patch-package)

```shell
npm install patch-package
```

add script to `package.json`

```json
"postinstall": "patch-package"
```

Edit `node_modules\fast-url-parser\src\urlparser.js`
Line `401`

Change

```javascript
var punycode = require("punycode");
```

to

```javascript
var punycode = require("punycode/");
```

then execute

```shell
npx patch-package fast-url-parser
```

To verify, execute again:

```shell
npx serve -v
```

For package managers other than npm, see [README](https://github.com/ds300/patch-package/blob/master/README.md) of [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by tik9** [comment]
Should I execute the code on top `mkdir serve-test..` and then execute the workaround?

**Comment by MikeMcC399** [comment]
@tik9 

> Should I execute the code on top `mkdir serve-test..` and then execute the workaround?

You would replace `serve-test` with the name of your existing repository. Sorry if that was not clear. I just used the name `serve-test` to demonstrate the principal of patching. You wouldn't normally be creating a new directory if you already have a repository that you are going to patch.

**Comment by MikeMcC399** [comment]
- Re-submitted as issue #802 

Node.js 21 is now in maintenance reaches [end-of-life](https://github.com/nodejs/release#release-schedule) on June 1, 2024.
